- name: Start docker container Nginx
  community.docker.docker_container:
    name: nginx
    image: nginx:stable-perl
    ports:
      - "9999:9999"
    volumes:
      - /home/parallels/Downloads/Viettel-Digital-Talent-2023/3. Midterm/Vu_Minh_Hieu/ansible/roles/nginx/files/web.conf:/etc/nginx/conf.d/default.conf