name: CI & CD

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["main"]

env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: cd 3.\ Midterm/Vu_Minh_Hieu/ && docker-compose build --no-cache --force-rm

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create fresh env to test
              run: cd 3.\ Midterm/Vu_Minh_Hieu/ && docker-compose up -d mongodb
            - name: Install local dependencies
              run: cd 3.\ Midterm/Vu_Minh_Hieu/backend/ && pip install -r requirements.txt
            - name: Run the unittest
              run: cd 3.\ Midterm/Vu_Minh_Hieu/backend/ &&  pytest
