name: Unit test

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - main

env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker-compose -f 3.\ Midterm/Vu_Minh_Hieu/docker-compose.yml build --no-cache --force-rm

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            - name: Create fresh env to test
              run: docker-compose -f 3.\ Midterm/Vu_Minh_Hieu/docker-compose.yml up -d mongodb
            - name: Install local dependencies
              run: pip install -r 3.\ Midterm/Vu_Minh_Hieu/backend/requirements.txt
            - name: Run the unittest
              run: pytest 3.\ Midterm/Vu_Minh_Hieu/backend/
